version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - packages/**/node_modules
          key: v3-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: yarn test:back:ci
      # run linter
      - run: yarn lint:front --max-warnings=0
      - run: yarn lint:back --max-warnings=0

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
